delete from group_category;
insert into group_category(id,name) values(18,"Athletics");
insert into group_category(id,name) values(17,"Art & Design");
insert into group_category(id,name) values(16,"Academic Government");
insert into group_category(id,name) values(15,"Academic Clubs & Societies");
insert into group_category(id,name) values(14,"Business/Economics");
insert into group_category(id,name) values(13,"Community");
insert into group_category(id,name) values(12,"Family");
insert into group_category(id,name) values(11,"Music");
insert into group_category(id,name) values(10,"Media & Entertainment");
insert into group_category(id,name) values(9,"Military");
insert into group_category(id,name) values(8,"Gaming");
insert into group_category(id,name) values(7,"Religious");
insert into group_category(id,name) values(6,"Residential/Campus Life");
insert into group_category(id,name) values(5,"Science & Technology");
insert into group_category(id,name) values(4,"Social Sciences & Humanities");
insert into group_category(id,name) values(3,"Volunteering");
insert into group_category(id,name) values(2,"Workplace");
insert into group_category(id,name) values(1,"Other");
update group_category set alias = name;
update group_category set alias = "xxxxx" where name="Other";