delete from group_org;
insert into group_org(name) values("Other - Not Listed or Not School Affiliated");
insert into group_org(name) values("Abraham Lincoln High");
insert into group_org(name) values("Abraxis Charter");
insert into group_org(name) values("Academy of Chinese Culture and Health Sciences");
insert into group_org(name) values("Adrian Wilcox High");
insert into group_org(name) values("Alameda County Opportunity");
insert into group_org(name) values("Alameda High");
insert into group_org(name) values("Alameda Science and Technology Institute");
insert into group_org(name) values("Albany High");
insert into group_org(name) values("Ali Akbar College of Music");
insert into group_org(name) values("Alta Vista High");
insert into group_org(name) values("Alternative Crossroads High");
insert into group_org(name) values("Alternative Learning Academy at Conley-C");
insert into group_org(name) values("Alternative Liberty High");
insert into group_org(name) values("Alternative Placement Academy");
insert into group_org(name) values("Alternative Street Academy");
insert into group_org(name) values("Alternative Tamiscal High");
insert into group_org(name) values("Alternative Valley Oaks High");
insert into group_org(name) values("Amador Valley High");
insert into group_org(name) values("American High");
insert into group_org(name) values("American Indian Public High");
insert into group_org(name) values("Analy High");
insert into group_org(name) values("Andrew P. Hill High");
insert into group_org(name) values("Animation Mentor");
insert into group_org(name) values("Ann Sobrato High");
insert into group_org(name) values("Apollo High");
insert into group_org(name) values("Aragon High");
insert into group_org(name) values("Argosy University");
insert into group_org(name) values("ARISE High");
insert into group_org(name) values("Arques School of Traditional Boatbuilding");
insert into group_org(name) values("Arroyo High");
insert into group_org(name) values("Aspire East Palo Alto Phoenix Academy");
insert into group_org(name) values("Bay Area School of Enterprise");
insert into group_org(name) values("Berkeley City College");
insert into group_org(name) values("Berkeley High");
insert into group_org(name) values("Berkeley Technology Academy");
insert into group_org(name) values("Boynton High");
insert into group_org(name) values("Branham High");
insert into group_org(name) values("Brenkwitz High");
insert into group_org(name) values("Broadway High");
insert into group_org(name) values("Brooks College");
insert into group_org(name) values("Buena Vista High");
insert into group_org(name) values("Burlingame High");
insert into group_org(name) values("Calaveras Hills");
insert into group_org(name) values("California College of the Arts");
insert into group_org(name) values("California South Bay University");
insert into group_org(name) values("California State Normal School");
insert into group_org(name) values("California State University, East Bay");
insert into group_org(name) values("California University of Management and Technology");
insert into group_org(name) values("Camden Community Day");
insert into group_org(name) values("Camp Glenwood");
insert into group_org(name) values("Cañada College");
insert into group_org(name) values("Canyon Oaks Youth Center");
insert into group_org(name) values("Capuchino High");
insert into group_org(name) values("Carlmont High");
insert into group_org(name) values("Carnegie Mellon Silicon Valley");
insert into group_org(name) values("Casa Grande High");
insert into group_org(name) values("Castlemont High");
insert into group_org(name) values("Castro Valley High");
insert into group_org(name) values("Chabot College");
insert into group_org(name) values("Christopher High");
insert into group_org(name) values("Church Divinity School of the Pacific");
insert into group_org(name) values("Civicorps Corpsmember Academy");
insert into group_org(name) values("Cloverdale High");
insert into group_org(name) values("Cogswell Polytechnical College");
insert into group_org(name) values("College of Alameda");
insert into group_org(name) values("College of Marin");
insert into group_org(name) values("College of San Mateo");
insert into group_org(name) values("Community Day");
insert into group_org(name) values("Continuation Baden High");
insert into group_org(name) values("Continuation Bridgepoint High");
insert into group_org(name) values("Continuation Carpe Diem High");
insert into group_org(name) values("Continuation Central High");
insert into group_org(name) values("Continuation Community Career Academy");
insert into group_org(name) values("Continuation Gunderson Plus");
insert into group_org(name) values("Continuation Island High");
insert into group_org(name) values("Continuation Leland Plus");
insert into group_org(name) values("Continuation Lincoln High");
insert into group_org(name) values("Continuation MacGregor High");
insert into group_org(name) values("Continuation Madrone High");
insert into group_org(name) values("Continuation Peninsula High");
insert into group_org(name) values("Continuation Phoenix High");
insert into group_org(name) values("Continuation Ridgway High");
insert into group_org(name) values("Continuation Robertson High");
insert into group_org(name) values("Continuation Royal Sunset");
insert into group_org(name) values("Continuation San Andreas High");
insert into group_org(name) values("Continuation San Antonio High");
insert into group_org(name) values("Continuation Sonoma Mountain High");
insert into group_org(name) values("Continuation Valley High");
insert into group_org(name) values("Continuation Willow Glen Plus");
insert into group_org(name) values("Core Learning Academy at Conley-Caraball");
insert into group_org(name) values("County Community");
insert into group_org(name) values("Credo High");
insert into group_org(name) values("Creekside High");
insert into group_org(name) values("Cupertino High");
insert into group_org(name) values("De Anza College");
insert into group_org(name) values("Del Mar High");
insert into group_org(name) values("Del Valle Continuation High");
insert into group_org(name) values("DeVry University");
insert into group_org(name) values("Dewey Academy");
insert into group_org(name) values("Dominican School of Philosophy and Theology");
insert into group_org(name) values("Dominican University of California");
insert into group_org(name) values("Downtown College Preparatory");
insert into group_org(name) values("Dr. T. J. Owens Gilroy Early College Academy");
insert into group_org(name) values("Dublin High");
insert into group_org(name) values("East Bay Arts High");
insert into group_org(name) values("East Oakland Leadership Academy High");
insert into group_org(name) values("El Camino High");
insert into group_org(name) values("El Molino High");
insert into group_org(name) values("Elsie Allen High");
insert into group_org(name) values("Emery Secondary");
insert into group_org(name) values("Empire College");
insert into group_org(name) values("Empire College School of Law");
insert into group_org(name) values("Encinal High");
insert into group_org(name) values("Envision Academy for Arts & Technology");
insert into group_org(name) values("Escuela Popular/Center for Training and");
insert into group_org(name) values("Everest Public High");
insert into group_org(name) values("Evergreen Valley College");
insert into group_org(name) values("Evergreen Valley High");
insert into group_org(name) values("Ex'pression College for Digital Arts");
insert into group_org(name) values("Five Branches University");
insert into group_org(name) values("Foothill College");
insert into group_org(name) values("Foothill High");
insert into group_org(name) values("Foothill-De Anza Community College District");
insert into group_org(name) values("Franciscan School of Theology");
insert into group_org(name) values("Fremont High");
insert into group_org(name) values("Fuller Northern California");
insert into group_org(name) values("Gateway Center");
insert into group_org(name) values("Gateway to College at Laney College");
insert into group_org(name) values("Gateway");
insert into group_org(name) values("Gavilan College");
insert into group_org(name) values("Geyserville Educational Park High");
insert into group_org(name) values("Gilroy High");
insert into group_org(name) values("Golden Gate Baptist Theological Seminary");
insert into group_org(name) values("Golden State Baptist College");
insert into group_org(name) values("Grace High");
insert into group_org(name) values("Graduate Theological Union");
insert into group_org(name) values("Granada High");
insert into group_org(name) values("Gunderson High");
insert into group_org(name) values("Half Moon Bay High");
insert into group_org(name) values("Hayward High");
insert into group_org(name) values("Heald College");
insert into group_org(name) values("Healdsburg High");
insert into group_org(name) values("Henley-Putnam University");
insert into group_org(name) values("Henry M. Gunn High");
insert into group_org(name) values("Herguan University");
insert into group_org(name) values("Hillcrest at Youth Services Center");
insert into group_org(name) values("Hillsdale High");
insert into group_org(name) values("Hillside Academy");
insert into group_org(name) values("Holy Names University");
insert into group_org(name) values("Homestead High");
insert into group_org(name) values("Impact Academy of Arts & Technology");
insert into group_org(name) values("Independence High");
insert into group_org(name) values("Insight School of California - North Bay");
insert into group_org(name) values("Institute of Transpersonal Psychology");
insert into group_org(name) values("International Technological University");
insert into group_org(name) values("Irvington High");
insert into group_org(name) values("James Lick High");
insert into group_org(name) values("James Logan High");
insert into group_org(name) values("Jefferson High");
insert into group_org(name) values("Jesuit School of Theology of Santa Clara University");
insert into group_org(name) values("Johanna Echols-Hansen High (Continuation)");
insert into group_org(name) values("John F. Kennedy High");
insert into group_org(name) values("John F. Kennedy University");
insert into group_org(name) values("KIPP King Collegiate High");
insert into group_org(name) values("KIPP San Jose Collegiate");
insert into group_org(name) values("Laguna High");
insert into group_org(name) values("Laney College");
insert into group_org(name) values("Las Positas College");
insert into group_org(name) values("Latino College Preparatory Academy");
insert into group_org(name) values("Leadership Public Schools - Hayward");
insert into group_org(name) values("Leadership Public Schools - San Jose");
insert into group_org(name) values("Leigh High");
insert into group_org(name) values("Leland High");
insert into group_org(name) values("Lewis Opportunity");
insert into group_org(name) values("Lighthouse Community Charter High");
insert into group_org(name) values("Lincoln Plus High");
insert into group_org(name) values("Lincoln University (California)");
insert into group_org(name) values("Live Oak High");
insert into group_org(name) values("Livermore High");
insert into group_org(name) values("Livermore Valley Charter Preparatory Hig");
insert into group_org(name) values("Lone Mountain College");
insert into group_org(name) values("Los Altos High");
insert into group_org(name) values("Los Gatos High");
insert into group_org(name) values("LPS College Park");
insert into group_org(name) values("Lynbrook High");
insert into group_org(name) values("Marce Becerra Academy");
insert into group_org(name) values("Maria Carrillo High");
insert into group_org(name) values("Marin County Community");
insert into group_org(name) values("Marin County Juvenile Court");
insert into group_org(name) values("Marin Oaks High");
insert into group_org(name) values("McClymonds High");
insert into group_org(name) values("Menlo College");
insert into group_org(name) values("Menlo-Atherton High");
insert into group_org(name) values("Merritt College");
insert into group_org(name) values("Mesa High");
insert into group_org(name) values("MetWest High");
insert into group_org(name) values("Middle College High");
insert into group_org(name) values("Midrose High");
insert into group_org(name) values("Millennium High Alternative");
insert into group_org(name) values("Mills College");
insert into group_org(name) values("Mills High");
insert into group_org(name) values("Milpitas High");
insert into group_org(name) values("Mission College (California)");
insert into group_org(name) values("Mission San Jose High");
insert into group_org(name) values("Montgomery High");
insert into group_org(name) values("Mountain View High");
insert into group_org(name) values("Mt. Eden High");
insert into group_org(name) values("Mt. Madonna High");
insert into group_org(name) values("Mt. Pleasant High");
insert into group_org(name) values("National Hispanic University");
insert into group_org(name) values("National University (California)");
insert into group_org(name) values("New College of California");
insert into group_org(name) values("New Valley Continuation High");
insert into group_org(name) values("Newark Memorial High");
insert into group_org(name) values("Northwest Prep at Piner-Olivet");
insert into group_org(name) values("Northwestern Polytechnic University");
insert into group_org(name) values("Notre Dame de Namur University");
insert into group_org(name) values("Nova Education Center");
insert into group_org(name) values("Novato High");
insert into group_org(name) values("Nueva Vista High");
insert into group_org(name) values("Oak Grove High");
insert into group_org(name) values("Oakland Charter High");
insert into group_org(name) values("Oakland High");
insert into group_org(name) values("Oakland International High");
insert into group_org(name) values("Oakland Technical High");
insert into group_org(name) values("Oakland Unity High");
insert into group_org(name) values("Oaksterdam University");
insert into group_org(name) values("Oceana High");
insert into group_org(name) values("Ohlone College");
insert into group_org(name) values("Palo Alto High");
insert into group_org(name) values("Palo Alto University");
insert into group_org(name) values("Patten University");
insert into group_org(name) values("Pegasus High");
insert into group_org(name) values("Pescadero High");
insert into group_org(name) values("Petaluma High");
insert into group_org(name) values("Phoenix Academy");
insert into group_org(name) values("Phoenix High");
insert into group_org(name) values("Piedmont High");
insert into group_org(name) values("Piedmont Hills High");
insert into group_org(name) values("Pilarcitos Alternative High (Continuatio)");
insert into group_org(name) values("Piner High");
insert into group_org(name) values("Pioneer High");
insert into group_org(name) values("Pivot Online Charter - North Bay");
insert into group_org(name) values("Prison University Project");
insert into group_org(name) values("Prospect High");
insert into group_org(name) values("Ralph J. Bunche High");
insert into group_org(name) values("Rancho Cotate High");
insert into group_org(name) values("REALM High");
insert into group_org(name) values("Redwood Continuation High");
insert into group_org(name) values("Redwood High");
insert into group_org(name) values("Rudsdale Continuation");
insert into group_org(name) values("Saint Patrick's Seminary and University");
insert into group_org(name) values("Samuel Merritt University");
insert into group_org(name) values("San Francisco Theological Seminary");
insert into group_org(name) values("San Jose City College");
insert into group_org(name) values("San Jose Community High");
insert into group_org(name) values("San Jose Conservation Corps Charter");
insert into group_org(name) values("San Jose High Academy Plus");
insert into group_org(name) values("San Jose High");
insert into group_org(name) values("San Jose State University");
insert into group_org(name) values("San Leandro High");
insert into group_org(name) values("San Lorenzo High");
insert into group_org(name) values("San Marin High School-Plus");
insert into group_org(name) values("San Marin High");
insert into group_org(name) values("San Mateo High");
insert into group_org(name) values("San Rafael High");
insert into group_org(name) values("Santa Clara Community Day");
insert into group_org(name) values("Santa Clara County Juvenile Hall");
insert into group_org(name) values("Santa Clara High");
insert into group_org(name) values("Santa Clara University");
insert into group_org(name) values("Santa Rosa High");
insert into group_org(name) values("Santa Rosa Junior College");
insert into group_org(name) values("Santa Teresa High");
insert into group_org(name) values("Saratoga High");
insert into group_org(name) values("Sequoia Community Day");
insert into group_org(name) values("Sequoia High");
insert into group_org(name) values("Silicon Valley University");
insert into group_org(name) values("Silver Creek High");
insert into group_org(name) values("Sir Francis Drake High");
insert into group_org(name) values("Skyline College");
insert into group_org(name) values("Skyline High");
insert into group_org(name) values("Sonoma State University");
insert into group_org(name) values("Sonoma Valley High");
insert into group_org(name) values("South San Francisco High");
insert into group_org(name) values("Stanford University");
insert into group_org(name) values("Summit Preparatory Charter High");
insert into group_org(name) values("Summit Public School: Rainier");
insert into group_org(name) values("Summit Public School: Tahoma");
insert into group_org(name) values("Tamalpais High");
insert into group_org(name) values("Technology High");
insert into group_org(name) values("Tennyson High");
insert into group_org(name) values("Terra Linda High");
insert into group_org(name) values("Terra Nova High");
insert into group_org(name) values("The Art Institute of California – Sunnyvale");
insert into group_org(name) values("Thornton High");
insert into group_org(name) values("Tomales High");
insert into group_org(name) values("UC Berkeley School of Law");
insert into group_org(name) values("University of California, Berkeley");
insert into group_org(name) values("University of Northern California (Santa Rosa)");
insert into group_org(name) values("University of San Francisco");
insert into group_org(name) values("University Preparatory Academy Charter");
insert into group_org(name) values("Village High");
insert into group_org(name) values("Vista Alternative");
insert into group_org(name) values("Washington High");
insert into group_org(name) values("West Valley College");
insert into group_org(name) values("Western Seminary");
insert into group_org(name) values("Westmont High");
insert into group_org(name) values("Westmoor High");
insert into group_org(name) values("William C. Overfelt High");
insert into group_org(name) values("William Jessup University");
insert into group_org(name) values("Willow Glen High");
insert into group_org(name) values("Wilson Alternative");
insert into group_org(name) values("Windsor High");
insert into group_org(name) values("Windsor Oaks Academy");
insert into group_org(name) values("Woodside High");
insert into group_org(name) values("World College West");
insert into group_org(name) values("Wright Institute");
insert into group_org(name) values("WSCUHSD Community Day");
insert into group_org(name) values("WyoTech");
insert into group_org(name) values("Yerba Buena High");
insert into group_org(name) values("Zaytuna College");

update group_org set alias = name;
update group_org set alias = "AAAAAAA" where name="Other - Not Listed or Not School Affiliated";
